FROM golang:1.26-alpine AS builder

RUN apk add --no-cache git

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

FROM alpine:3.22

WORKDIR /app

RUN apk add --no-cache \
    ca-certificates \
    netcat-openbsd

COPY --from=builder /go/bin/goose /bin/goose

COPY migrations ./migrations
COPY docker/migrate.sh /migrate.sh

RUN chmod +x /migrate.sh

ENTRYPOINT ["/migrate.sh"]