// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: documentprocessor/v1/document_processor.proto

package documentprocessorv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	UploadedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_documentprocessor_v1_document_processor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_documentprocessor_v1_document_processor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Document) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Document) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

func (x *Document) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	mi := &file_documentprocessor_v1_document_processor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_documentprocessor_v1_document_processor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{1}
}

func (x *ListDocumentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDocumentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsResponse) Reset() {
	*x = ListDocumentsResponse{}
	mi := &file_documentprocessor_v1_document_processor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse) ProtoMessage() {}

func (x *ListDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_documentprocessor_v1_document_processor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{2}
}

func (x *ListDocumentsResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *ListDocumentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_documentprocessor_v1_document_processor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_documentprocessor_v1_document_processor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{3}
}

func (x *GetDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UploadDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDocumentRequest) Reset() {
	*x = UploadDocumentRequest{}
	mi := &file_documentprocessor_v1_document_processor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentRequest) ProtoMessage() {}

func (x *UploadDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_documentprocessor_v1_document_processor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentRequest.ProtoReflect.Descriptor instead.
func (*UploadDocumentRequest) Descriptor() ([]byte, []int) {
	return file_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{4}
}

func (x *UploadDocumentRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadDocumentRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type UploadDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDocumentResponse) Reset() {
	*x = UploadDocumentResponse{}
	mi := &file_documentprocessor_v1_document_processor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentResponse) ProtoMessage() {}

func (x *UploadDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_documentprocessor_v1_document_processor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentResponse.ProtoReflect.Descriptor instead.
func (*UploadDocumentResponse) Descriptor() ([]byte, []int) {
	return file_documentprocessor_v1_document_processor_proto_rawDescGZIP(), []int{5}
}

func (x *UploadDocumentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadDocumentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_documentprocessor_v1_document_processor_proto protoreflect.FileDescriptor

const file_documentprocessor_v1_document_processor_proto_rawDesc = "" +
	"\n" +
	"-documentprocessor/v1/document_processor.proto\x12\x14documentprocessor.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\x01\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12;\n" +
	"\vuploaded_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadedAt\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"G\n" +
	"\x14ListDocumentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"k\n" +
	"\x15ListDocumentsResponse\x12<\n" +
	"\tdocuments\x18\x01 \x03(\v2\x1e.documentprocessor.v1.DocumentR\tdocuments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"$\n" +
	"\x12GetDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"N\n" +
	"\x15UploadDocumentRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"@\n" +
	"\x16UploadDocumentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xfd\x02\n" +
	"\x0fDocumentService\x12\x83\x01\n" +
	"\rListDocuments\x12*.documentprocessor.v1.ListDocumentsRequest\x1a+.documentprocessor.v1.ListDocumentsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/documents\x12w\n" +
	"\vGetDocument\x12(.documentprocessor.v1.GetDocumentRequest\x1a\x1e.documentprocessor.v1.Document\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/documents/{id}\x12k\n" +
	"\x0eUploadDocument\x12+.documentprocessor.v1.UploadDocumentRequest\x1a,.documentprocessor.v1.UploadDocumentResponseBfZdgithub.com/knowledge-search-system/document-processor/proto/documentprocessor/v1;documentprocessorv1b\x06proto3"

var (
	file_documentprocessor_v1_document_processor_proto_rawDescOnce sync.Once
	file_documentprocessor_v1_document_processor_proto_rawDescData []byte
)

func file_documentprocessor_v1_document_processor_proto_rawDescGZIP() []byte {
	file_documentprocessor_v1_document_processor_proto_rawDescOnce.Do(func() {
		file_documentprocessor_v1_document_processor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_documentprocessor_v1_document_processor_proto_rawDesc), len(file_documentprocessor_v1_document_processor_proto_rawDesc)))
	})
	return file_documentprocessor_v1_document_processor_proto_rawDescData
}

var file_documentprocessor_v1_document_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_documentprocessor_v1_document_processor_proto_goTypes = []any{
	(*Document)(nil),               // 0: documentprocessor.v1.Document
	(*ListDocumentsRequest)(nil),   // 1: documentprocessor.v1.ListDocumentsRequest
	(*ListDocumentsResponse)(nil),  // 2: documentprocessor.v1.ListDocumentsResponse
	(*GetDocumentRequest)(nil),     // 3: documentprocessor.v1.GetDocumentRequest
	(*UploadDocumentRequest)(nil),  // 4: documentprocessor.v1.UploadDocumentRequest
	(*UploadDocumentResponse)(nil), // 5: documentprocessor.v1.UploadDocumentResponse
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
}
var file_documentprocessor_v1_document_processor_proto_depIdxs = []int32{
	6, // 0: documentprocessor.v1.Document.uploaded_at:type_name -> google.protobuf.Timestamp
	0, // 1: documentprocessor.v1.ListDocumentsResponse.documents:type_name -> documentprocessor.v1.Document
	1, // 2: documentprocessor.v1.DocumentService.ListDocuments:input_type -> documentprocessor.v1.ListDocumentsRequest
	3, // 3: documentprocessor.v1.DocumentService.GetDocument:input_type -> documentprocessor.v1.GetDocumentRequest
	4, // 4: documentprocessor.v1.DocumentService.UploadDocument:input_type -> documentprocessor.v1.UploadDocumentRequest
	2, // 5: documentprocessor.v1.DocumentService.ListDocuments:output_type -> documentprocessor.v1.ListDocumentsResponse
	0, // 6: documentprocessor.v1.DocumentService.GetDocument:output_type -> documentprocessor.v1.Document
	5, // 7: documentprocessor.v1.DocumentService.UploadDocument:output_type -> documentprocessor.v1.UploadDocumentResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_documentprocessor_v1_document_processor_proto_init() }
func file_documentprocessor_v1_document_processor_proto_init() {
	if File_documentprocessor_v1_document_processor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_documentprocessor_v1_document_processor_proto_rawDesc), len(file_documentprocessor_v1_document_processor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_documentprocessor_v1_document_processor_proto_goTypes,
		DependencyIndexes: file_documentprocessor_v1_document_processor_proto_depIdxs,
		MessageInfos:      file_documentprocessor_v1_document_processor_proto_msgTypes,
	}.Build()
	File_documentprocessor_v1_document_processor_proto = out.File
	file_documentprocessor_v1_document_processor_proto_goTypes = nil
	file_documentprocessor_v1_document_processor_proto_depIdxs = nil
}
