name: Document Processor CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # document-processor
      - name: Extract Docker metadata (document-processor)
        id: meta-document-processor
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and Push document-processor
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta-document-processor.outputs.tags }}
          labels: ${{ steps.meta-document-processor.outputs.labels }}

      # document-processor-migrate
      - name: Extract Docker metadata (migrate)
        id: meta-migrate
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-migrate

      - name: Build and Push document-processor-migrate
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.migrate
          push: true
          tags: ${{ steps.meta-migrate.outputs.tags }}
          labels: ${{ steps.meta-migrate.outputs.labels }}